name: 'check-and-wait'
description: 'Check if a workflow is running and wait for it to finish'
inputs:
  workflow:
    description: 'Name of the workflow to check'
    required: true

  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check if terraform workflow is started
      id: check-terraform-workflow
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

      shell: bash
      run: |
        echo "is_running=$(bash .github/scripts/check-terraform-workflow.sh '${{ inputs.workflow }}' ${{ github.repository }})" >> $GITHUB_OUTPUT

    - name: Wait for tests to succeed
      if: steps.check-terraform-workflow.outputs.is_running == 'true'
      uses: lewagon/wait-on-check-action@v1.3.4
      with:
        ref: ${{ github.ref }}
        check-name: Terraform
        repo-token: ${{ inputs.github-token }}
        wait-interval: 10
        allowed-conclusions: success