name: Flutter App CI/CD

on:
#  workflow_dispatch:
#  release:
#    types: [ published ]

  pull_request:
    branches:
      - main
    paths:
      - 'packages/app/**'
      - '.github/workflows/app.yml'

env:
  CI: true

defaults:
  run:
    working-directory: packages/app

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    env:
      AAB_PATH: packages/app/build/app/outputs/bundle/release/app-release.aab
      KEYSTORE_PATH: android/upload-keystore.jks
      KEY_PROPS_PATH: android/key.properties
      SERVICE_ACCOUNT_PATH: store_credentials.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-install-cache

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Decode Android keystore
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > ${{ env.KEYSTORE_PATH }}

      - name: Copy keystore
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: cp ${{ env.KEYSTORE_PATH }} android/app/upload-keystore.jks

      - name: Decode Android key properties
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" | base64 --decode > ${{ env.KEY_PROPS_PATH }}

      - name: Decode Android Service Account
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "${{ secrets.PRODUCTION_CREDENTIAL_FILE }}" | base64 --decode > ${{ env.SERVICE_ACCOUNT_PATH }}

      - name: Build aab
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          flutter build appbundle \
            --release

      - name: Deploy to Play Store (Internal testing)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: packages/app/${{ env.SERVICE_ACCOUNT_PATH }}
          packageName: com.hollybike.hollybike
          releaseFiles: ${{ env.AAB_PATH }}
          status: draft
          track: internal
