name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

env:
  CI: true

defaults:
  run:
    working-directory: packages/backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up JDK 20
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'adopt'
#          java-version: '20'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Read rights to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test