name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'packages/backend/**'
      - '.github/workflows/backend.yml'

env:
  CI: true

defaults:
  run:
    working-directory: packages/backend

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Read rights to gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test