name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'packages/backend/**'
      - '.github/workflows/backend.yml'

env:
  CI: true

defaults:
  run:
    working-directory: packages/backend

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Read rights to gradlew
        run: chmod +x gradlew

#      - name: Run tests
#        run: ./gradlew test

      - name: Run native compile
        run: ./gradlew nativeCompile -Pimage_name=hollybike_server

      - name: Check and wait for workflow ${{ vars.INFRA_WORKFLOW }} to finish
        uses: ./.github/actions/check-and-wait
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          workflow: ${{ vars.INFRA_WORKFLOW }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload to AWS
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "Upload"