name: Export Secret to File

on:
  workflow_dispatch:

jobs:
  export-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Create files from secrets
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android_keystore.jks
          echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" | base64 --decode > android_key.properties

      - name: Upload ANDROID_KEYSTORE file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ANDROID_KEYSTORE
          path: android_keystore.jks

      - name: Upload ANDROID_KEY_PROPERTIES file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ANDROID_KEY_PROPERTIES
          path: android_key.properties