name: Frontend CI/CD

on:
#  release:
#    types: [ published ]

  workflow_call:

  pull_request:
    branches:
      - main
    paths:
      - 'packages/frontend/**'
      - '.github/workflows/frontend.yml'

env:
  CI: true

defaults:
  run:
    working-directory: packages/frontend

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    permissions:
      checks: read
      contents: read
      actions: read

    steps:
      - name: Echo event
        run: echo ${{ toJson(github.event) }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

      - name: Try building application
        run: bun run build

      - name: Upload artifacts
        # if it a workflow_call event
        if: github.event_name == 'workflow_call'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-${{ github.event.release.tag_name }}
          path: packages/frontend/dist
          retention-days: 1

      - name: Configure AWS credentials
        if: github.event_name == 'workflow_call'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Check and wait for workflow ${{ vars.INFRA_WORKFLOW }} to finish
        if: github.event_name == 'workflow_call'
        uses: ./.github/actions/check-and-wait
        with:
          workflow: ${{ vars.INFRA_WORKFLOW }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync cacheable files with S3 bucket
        if: github.event_name == 'workflow_call'
        run: aws s3 sync ./dist s3://${{ vars.AWS_S3_BUCKET }} --cache-control 'max-age=31536000' --exclude "*.html"

      - name: Sync non cacheable files with S3 bucket
        if: github.event_name == 'workflow_call'
        run: aws s3 sync ./dist s3://${{ vars.AWS_S3_BUCKET }} --cache-control 'no-cache'

      - name: Create CloudFront invalidation
        if: github.event_name == 'workflow_call'
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.AWS_CF_DIST_ID }} --paths "/*"