name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  # list folders changed in the packages/ directory
  changed_packages_folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get changed folders
        id: get_changed_folders
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep packages/ | cut -d/ -f2 | sort -u > changed_folders.txt
      - name: Set outputs
        id: set_outputs
        run: echo "::set-output name=changed_folders::$(cat changed_folders.txt)"

  # print the changed folders
  print_changed_folders:
    needs: changed_packages_folders
    runs-on: ubuntu-latest
    steps:
      - name: Print changed folders
        run: echo ${{ needs.changed_packages_folders.outputs.changed_folders }}