name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true

env:
  CI: true

permissions:
  checks: read
  contents: write
  actions: read

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          version: ${{ github.event.inputs.version }}
        run: |
          gh release create "$version" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/}-${version#v}" \
              --generate-notes

  build-backend:
    needs: create-release
    uses: ./.github/workflows/backend.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}