name: Release CI/CD

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  CI: true

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Try building application
        run: bun run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-${{ github.event.release.tag_name || 'snapshot' }}
          path: packages/frontend/dist
          retention-days: 1

  build-backend:
    name: Build Backend
    needs:
      - build-frontend
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java-version: [ '21' ]
        include:
          - os: ubuntu-latest
            executable-suffix: ''
          - os: windows-latest
            executable-suffix: '.exe'

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: packages/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM (Java ${{ matrix.java-version }})
        uses: graalvm/setup-graalvm@v1
        with:
          version: '${{ matrix.graalvm-version }}'
          java-version: '${{ matrix.java-version }}'
          cache: 'gradle'

      - name: Read rights to gradlew
        run: chmod +x gradlew

      - id: executable
        run: echo "executable_name=hollybike-${{ runner.os }}-${{ github.event.release.tag_name || 'snapshot' }}-x86_64" >> $GITHUB_OUTPUT

      - name: Remove files in ressources
        run: rm -rf src/main/resources/front/*

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-${{ github.event.release.tag_name || 'snapshot' }}
          path: packages/backend/src/main/resources/front/

      - name: Run native compile
        run: ./gradlew nativeCompile -Pimage_name=${{ steps.executable.outputs.executable_name }}

      - name: Upload release
        if: github.event.release.tag_name
        run: |
          gh release upload \
              ${{ github.event.release.tag_name }} \
              build/native/nativeCompile/${{ steps.executable.outputs.executable_name }}${{ matrix.executable-suffix }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}