name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true

env:
  CI: true

permissions:
  checks: read
  contents: write
  actions: read

jobs:
  create-release:
    name: Create Release
    needs: build-app
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          version: ${{ github.event.inputs.version }}
        run: |
          gh release create "$version" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/}-${version#v}" \
              --generate-notes

      - name: Get app artifact
        uses: actions/download-artifact@v4
        with:
          name: hollybike-Android-${{ github.event.release.tag_name }}
          path: .

      - name: Upload release
        run: |
          gh release upload \
              ${{ github.event.release.tag_name }} \
              hollybike-Android-${{ github.event.release.tag_name }}.apk

#  build-backend:
#    name: Build Frontend & Backend
#    needs: create-release
#    uses: ./.github/workflows/backend.yml
#    secrets:
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-app:
    name: Build App
    uses: ./.github/workflows/app.yml
    secrets:
      ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      ANDROID_KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}
      PRODUCTION_CREDENTIAL_FILE: ${{ secrets.PRODUCTION_CREDENTIAL_FILE }}