name: Release & Deploy

run-name: Release & Deploy HollyBike v${{ inputs.version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true

env:
  CI: true

permissions:
  checks: read
  contents: write
  actions: read
  packages: write

jobs:
  build-frontend-backend:
    name: Frontend & Backend
    uses: ./.github/workflows/backend.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-app:
    name: App
    uses: ./.github/workflows/app.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      ANDROID_KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}
      PRODUCTION_CREDENTIAL_FILE: ${{ secrets.PRODUCTION_CREDENTIAL_FILE }}

  create-release:
    name: Create Release
    needs:
      - build-app
      - build-frontend-backend
    runs-on: ubuntu-latest

    env:
      version: ${{ github.event.inputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get app artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: HollyBike-${{ env.version }}-*
          path: .

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
        run: |
          gh release create "$version" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/}-${version#v}" \
              --generate-notes \
              hollybike-Android-${{ env.version }}.apk \
              hollybike-Windows-${{ env.version }}-x86_64.exe \
              hollybike-Linux-${{ env.version }}-x86_64
